//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace registration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminDetailsTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AdminDetailsTable()
        {
            this.MotorClaimDetailsTables = new HashSet<MotorClaimDetailsTable>();
            this.MotorInsuranceTables = new HashSet<MotorInsuranceTable>();
            this.TravelClaimDetailsTables = new HashSet<TravelClaimDetailsTable>();
            this.TravelInsuranceTables = new HashSet<TravelInsuranceTable>();
        }
    
        public string Username { get; set; }
        public string Password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MotorClaimDetailsTable> MotorClaimDetailsTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MotorInsuranceTable> MotorInsuranceTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TravelClaimDetailsTable> TravelClaimDetailsTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TravelInsuranceTable> TravelInsuranceTables { get; set; }
    }
}
