//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace registration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MotorInsuranceTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MotorInsuranceTable()
        {
            this.MotorClaimDetailsTables = new HashSet<MotorClaimDetailsTable>();
            this.TransactionTables = new HashSet<TransactionTable>();
        }
    
        public long Policy_Id { get; set; }
        public Nullable<int> Number_Of_Wheels { get; set; }
        public string Manufacturer { get; set; }
        public string Model_Name { get; set; }
        public string Registration_Number { get; set; }
        public string RTA_Name { get; set; }
        public string Engine_Number { get; set; }
        public string Chassis_Number { get; set; }
        public Nullable<int> Year_Of_Manufacture { get; set; }
        public Nullable<System.DateTime> Purchase_Date { get; set; }
        public string Mobile_Number { get; set; }
        public string Insurance_Plan { get; set; }
        public Nullable<int> Time_Period { get; set; }
        public Nullable<System.DateTime> Policy_Start_Date { get; set; }
        public Nullable<System.DateTime> Policy_End_Date { get; set; }
        public string Insurer_Username { get; set; }
        public string Driving_License_Number { get; set; }
        public string Status { get; set; }
    
        public virtual AdminDetailsTable AdminDetailsTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MotorClaimDetailsTable> MotorClaimDetailsTables { get; set; }
        public virtual UserDetailsTable UserDetailsTable { get; set; }
        public virtual VehicleListTable VehicleListTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionTable> TransactionTables { get; set; }
    }
}
