//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace registration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionTable
    {
        public long Transaction_Id { get; set; }
        public Nullable<long> Motor_Policy_Id { get; set; }
        public Nullable<long> Travel_Policy_Id { get; set; }
        public Nullable<double> Premium_Amount { get; set; }
        public Nullable<System.DateTime> Payment_Date { get; set; }
        public string Transaction_Status { get; set; }
    
        public virtual MotorInsuranceTable MotorInsuranceTable { get; set; }
        public virtual TravelInsuranceTable TravelInsuranceTable { get; set; }
    }
}
