//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace registration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TravelClaimDetailsTable
    {
        public long Travel_Claim_Id { get; set; }
        public Nullable<long> Travel_Policy_Id { get; set; }
        public string Ticket_Copy { get; set; }
        public string Reason_for_Claim { get; set; }
        public string Mobile_Number { get; set; }
        public Nullable<double> Amount_Sanctioned { get; set; }
        public string Claim_Status { get; set; }
        public string Complaint_Copy { get; set; }
        public string Approver_Username { get; set; }
    
        public virtual AdminDetailsTable AdminDetailsTable { get; set; }
        public virtual TravelInsuranceTable TravelInsuranceTable { get; set; }
    }
}
