//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace registration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDetailsTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserDetailsTable()
        {
            this.MotorInsuranceTables = new HashSet<MotorInsuranceTable>();
            this.TravelInsuranceTables = new HashSet<TravelInsuranceTable>();
        }
    
        public string Mobile_Number { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public string Email_Id { get; set; }
        public string Gender { get; set; }
        public string Door_Number { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        public string District { get; set; }
        public string State { get; set; }
        public string Pincode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MotorInsuranceTable> MotorInsuranceTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TravelInsuranceTable> TravelInsuranceTables { get; set; }
    }
}
