//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace registration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleListTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VehicleListTable()
        {
            this.MotorInsuranceTables = new HashSet<MotorInsuranceTable>();
        }
    
        public string Manufacturer { get; set; }
        public string Model_Name { get; set; }
        public Nullable<int> Cubic_Capacity { get; set; }
        public string Type_Of_Body { get; set; }
        public Nullable<int> Seating_Capacity { get; set; }
        public Nullable<double> Brand_New_Price { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MotorInsuranceTable> MotorInsuranceTables { get; set; }
    }
}
